# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hostctl
builds:
  - id: hostctl
    binary: hostctl
    main: main.go
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      darwin: macOS

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: guumaster
    name: hostctl

nfpms:
  - id: hostctl
    builds:
      - hostctl
    formats:
      - deb
    vendor: Guumaster
    homepage: https://github.com/guumaster/hostctl
    maintainer: guumaster <guuweb@gmail.com>
    description: manage your hosts file like a pro

brews:
  - name: hostctl
    github:
      owner: guumaster
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/guumaster/hostctl
    description: manage your hosts file like a pro
    commit_author:
      name: goreleaserbot
      email: guuweb@gmail.com
    caveats: "Remember to add sudo to modify your hosts file."

scoop:
  bucket:
    owner: guumaster
    name: hostctl
  homepage:  https://github.com/guumaster/hostctl
  description: manage your hosts file like a pro
  license: MIT

snapcrafts:
  - id: hostctl
    name: hostctl
    summary: manage your hosts file like a pro
    description: manage your hosts file like a pro.
    grade: stable
    confinement: strict
    license: MIT
    # Disabled until passed review on snap store
    publish: false
    apps:
      hostctl:
        plugs: ["system-files"]
    plugs:
      system-files:
        read:
          - /etc/hosts
        write:
          - /etc/hosts
